---
title: "Regional vibrancy explorer ver.0"
author: "Dr Won Do Lee"
name: "dashboard"
output_dir: docs
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    social: menu
    source_code: https://github.com/wondolee/KCA
    theme: simplex
---
본 연구는 행정안전부에서 한국지방행정연구원으로 위탁한 인구감소지역 지원방안 연구용역(빅데이터 분석)으로 지원된 연구이며, 소비활동 활력평가는 신용카드 소비 데이터를 기반으로 작성되었음.

```{r setup,message=FALSE, warning=FALSE, paged.print=FALSE,include=FALSE}
knitr::opts_chunk$set(
	message = FALSE,
	warning = FALSE,
	paged.print = FALSE
)
rm(list=ls())
library(flexdashboard)
library(dplyr)
library(leaflet)
library(DT)
library(ggplot2)
library(knitr)
library(sf)
library(ggrepel)
library(tibble)
library(leaflet.providers)
library(leaftime)
library(geojsonio)
setwd("d:/GIT/KCA/")
admin.data<-st_read('data/sig.re.shp')
admin.data<-st_transform(admin.data,4326)
hotspot<-readRDS("data/card.hotspot.type.rda")

index.data<-left_join(admin.data,hotspot,by=c("SIG_CD"="code"))
#index.data$type<-as.factor(index.data$type)
index.data<-st_transform(index.data,4326)
#levels(index.data$type)<-c("Not Sig.","Hot spot","Cold spot")
gi.map <- colorFactor(palette =c("#eeeeee","#FF0000","#0000FF","#999999"),
                      levels = c("Not sig.","Hot spot","Cold spot","Isolated"),index.data$type)
colnames(index.data)[1]<-c("code")

#int.data.tracks<-hotspot %>% select(code,date)
#int.data.tracks$date.time<-as.POSIXct(int.data.tracks$date,tz="UTC",format=c("%Y-%m-%d"))
#int.data.tracks$start<-strptime(int.data.tracks$date.time,c("%Y-%m-%d %H:%M:%OS"))
#int.data.tracks$end<-dplyr::lead(int.data.tracks$start,1)
#int.data.tracks.admin<-left_join(index.data,as.data.frame(int.data.tracks),by=c("code","date"))
#int.data.tracks.time <- geojsonio::geojson_json(int.data.tracks.admin %>% filter(year==2018,month<=2))
#pal <- colorFactor(palette =c("#eeeeee","#FF0000","#0000FF","#999999"),
 #                     levels = c("Not sig.","Hot spot","Cold #spot","Isolated"),
#                      int.data.tracks.admin$type)
#gi.map <- colorFactor(palette =c("#eeeeee","#FF0000","#0000FF","#999999"),
#                      levels = c("Not sig.","Hot spot","Cold spot","Isolated"),
#                      index.data$type)
```

Column {data-width=600}
-----------------------------------------------------------------------

### Map

```{r message=FALSE, warning=FALSE, paged.print=FALSE}


leaflet(index.data %>% filter(year==2018,month==1)) %>%
  addProviderTiles('CartoDB.Positron') %>%
  addPolygons(stroke="black",
              smoothFactor=0.1,
              color = ~gi.map(type),
              weight=1,
              fillOpacity = 0.5,
              label=~name,
              highlight=highlightOptions(
                color="black",
                bringToFront=TRUE)
              ) %>%
  leaflet::addLegend(pal=gi.map,values=~type,
                      opacity=0.7,title="소비활동 활력 hot/cold spot")


#leaflet() %>% addProviderTiles('CartoDB.Positron') %>%
 # addTimeline(int.data.tracks.admin,timelineOpts = timelineOptions(
  #  pointToLayer = htmlwidgets::JS(
#      "
#function(data, latlng) {
#  return L.circleMarker(latlng, {
#    radius: 3
#  })
#}
#"
#    ),
#    style = NULL
#  )
#)
```


Column {data-width=400}
-----------------------------------------------------------------------

### Table

```{r message=FALSE, warning=FALSE, paged.print=FALSE}
for.table<-as.data.frame(index.data)
for.table<-for.table %>% select (code,name,year,month,type,intensity,des.dep.area)
colnames(for.table)<-c("시군구코드","시군구명","연도","월","구분","강도","인구감소구분")
for.table$강도<-round(for.table$강도,digit=2)
for.table %>% DT::datatable(extensions = 'Buttons',options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

```


### Graph
```{r plotly graph panel,message=FALSE, warning=FALSE}
require(ggplot2)
require(showtext)
require(ggrepel)
require(geofacet)
font_add_google("Noto Sans KR", "notosanskr")
showtext_auto()
theme_map <- function(...) {
  theme_minimal() +
    theme(
      plot.title=element_text(size=rel(17),family="notosanskr",face="bold"), 
      plot.subtitle=element_text(size=rel(15),family="notosanskr",face="bold"), 
      text = element_text(family = "notosanskr", color = "black",size=rel(2)),
      #legend.title=element_text(size=rel(12),family="notosanskr",face="bold"), 
      #legend.text=element_text(size=rel(12),family="notosanskr"),
      axis.line = element_blank(),
      axis.text.x =element_text(size=rel(6),family="notosanskr",face="bold"),
      axis.text.y = element_text(size=rel(12),family="notosanskr",face="bold"),
      axis.ticks = element_blank(),
      axis.title.x = element_text(size=rel(12),family="notosanskr",face="bold"),
      axis.title.y = element_text(size=rel(12),family="notosanskr",face="bold"),
      strip.text = element_text(size=rel(15),family="notosanskr",colour="black",face="bold"),
      # panel.grid.minor = element_line(color = "#ebebe5", size = 0.2),
      panel.grid.major = element_line(color = "#ebebe5", size = 0.2),
      panel.grid.minor = element_blank(),
      panel.border = element_blank(),
      plot.caption=element_text(hjust = 1, size=rel(10),family="notosanskr"),
      plot.margin = unit(c(0.2,0.2,0.2,0.2), "cm"),
      ...
    )
}

ggplot(data=index.data,
                         aes(x=date,y=intensity,colour=type))+
  geom_bar(stat='summary',fun="mean",width=0.5,colour="grey80")+
  scale_colour_manual(values=c("#eeeeee","#FF0000","#0000FF","#999999"))+
  geom_smooth(method="loess",span=0.2,size=0.8,se=FALSE,show.legend=FALSE)+
  geom_line(colour="grey40",alpha=0.3)+
  #method = list(dl.combine("first.points","last.points"))
  #, cex = 1)+
  #facet_wrap(~type,ncol=6,nrow=3)+
  #coord_flip()+  
  scale_x_date(date_labels="%b",date_breaks="3 month")+
  scale_y_continuous(labels = scales::number_format())+
  #geom_hline(yintercept=0, linetype='dashed', color='black', size=0.2)+
  ylim(c(-1,1))+
  #geom_hline(yintercept=0,linetype=2,colour="gray20",size=0.3,alpha=0.8)+
  labs(x="연도 ('18~'22년 5월)",y="월별 소비활력 강도 (단위: 일별 중위값)",
       #subtitle="(단위: 전국 명목기준 GRDP 총액대비 비율)",
       #title="지역내총생산 비율"
       colour="지역구분")+
  theme_map()+
  theme(legend.title=element_text(size=rel(12),family="notosanskr",face="bold"), 
        legend.text=element_text(size=rel(12),family="notosanskr"))
```